services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: employee-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb+srv://yungblue023:yungblueazmildagoat369@project.unql5fh.mongodb.net/mcp_test?retryWrites=true&w=majority&appName=Project
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: employee-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
